### ISSUE TITLE
Decide on whether/how to ship Singularity image for the bagel-cli

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagel-cli#114]
On shared scientific infrastructure such as Compute Canada servers, we expect that users will not be able to use Docker. Since we will push an image for our Python CLI to Dockerhub, should we, for Singularity users:
1. Separately create a Singularity def file (and possibly push it to the container library, in which case it would be updated in sync with the Dockerhub image)
2. Only keep the Dockerfile / push to Dockerhub, and include in the README instructions for pulling and building a Singularity image from the Dockerhub image, if needed

**Comment by surchs** [comment]
@alyssadai: I would say we:

1. Focus on having up to date docker-hub images for the CLI
2. Do not provide a separate Singularity image but describe how to make one from the docker-hub ones
3. Close this issue
