### ISSUE TITLE
Ensure at least one column is "about" participant_id

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagel-cli#121]
We should ensure that a minimum of one column has the "isAbout" tag for participant_id, i.e. there is at least one column with subject identifiers.

_Originally posted by @alyssadai in https://github.com/neurobagel/bagel-cli/pull/120#discussion_r1170602298_

**Comment by surchs** [comment]
bumping this to roadmap as not priority right now.

**Comment by surchs** [comment]
This seems to still be unaddressed, would probably fit here https://github.com/neurobagel/bagel-cli/blob/5dea123c9e0c63c6e2d076751c705e2ceb3ab9cf/bagel/pheno_utils.py#L266

But maybe could be part of a refactor that puts each into their own function?

**Comment by alyssadai** [comment]
By "each", do you mean participant vs session column validation?
