### ISSUE TITLE
Switch controlled term namespaces to variables

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagel-cli#125]
We have controlled term namespace prefixes 'hard-coded' in several places in the CLI, e.g. instances of "bg" in https://github.com/neurobagel/bagel-cli/blob/main/bagel/pheno_utils.py and https://github.com/neurobagel/bagel-cli/blob/main/bagel/models.py, which currently makes updating them a bit tedious.

As an alternative, we could create a set of namedtuples to store all of our used namespaces, i.e. `Namespace = namedtuple("Namespace", ["pf", "url"])` (pf for prefix) and access the values elsewhere in the codebase using the field names instead of the actual string prefixes for example. This way, we can also reuse the named tuples to construct the context.

**Comment by alyssadai** [comment]
@surchs thoughts? Since I'm already updating the namespaces as part of https://github.com/neurobagel/bagel-cli/issues/124, I don't mind addressing this as well.

**Comment by surchs** [comment]
I think this makes sense (not totally sure what the plan is). But as usual, we can take liberal inspiration from what our friends over in dandi-land have done to handle this. They added an extra attribute to the models (e.g. here https://github.com/dandi/dandi-schema/blob/845cb17ea2d28275429d11286b38da3a265c16c4/dandischema/models.py#L878) and then use that when building the context to set the correct namespace: https://github.com/dandi/dandi-schema/blob/845cb17ea2d28275429d11286b38da3a265c16c4/dandischema/metadata.py#L61

Is that what you meant?
