### ISSUE TITLE
Capitalize age heuristics

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagel-cli#128]
Age heuristics are currently lowercase. According to the new naming standards, these probably are equivalent to resources and thus should be capitalized, e.g. nb:Float instead of nb:float (?)

_Originally posted by @surchs in https://github.com/neurobagel/bagel-cli/pull/127#discussion_r1188951514_

TODO:

- [x] Find names that better reflect that these are transformations. @alyssadai suggested `nb:FromISO8061` for example
*`ISO8061` implies that's the format the age gets stored as (target of the transformation) however, `FromISO8061` makes it explicit that it's a transformation from `ISO8061` to some other format*
- [x] Turn all of the transformations into PascalCase
- [x] Update 
  - [x] all of the corresponding docs
  - [x] CLI logic for transformation and corresponding tests
- [x] create corresponding issue on the annotation tool to address as part of reviving that

**Comment by surchs** [comment]
I think we should quickly discuss this and then either implement or close
