### ISSUE TITLE
Add identifiers of used controlled terms back into `@context`

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagel-cli#129]
Ever since we refactored models.py classes corresponding to controlled terms with only `identifier` and `schemaKey` attributes into a general `ControlledTerm` class (see https://github.com/neurobagel/bagel-cli/issues/110), the function which generates the context for the .jsonld (see below) no longer adds specific named instances of ControlledTerm and their URIs to the context. So, the following resources (representing types) currently can appear as schemaKeys in the .jsonld but currently are not mapped to a namespace in the created context:
- "Diagnosis"
- "Assessment"
- "Sex"
- "SubjectGroup"
- "Image"

https://github.com/neurobagel/bagel-cli/blob/827179c099a725457c16ad9c8525abca5574a03a/bagel/pheno_utils.py#L25-L48

### Fix
~- [ ] add namespace prefix to schemaKeys, e.g. `"schemaKey": "Sex"` becomes `"schemaKey": "nb:Sex"`~
- [x] **add back a separate named class for each controlled term**
  - [x] Keep ControlledTerms class and just inherit from it for each to-be-recreated classes (provide their schemaKey attribute on instantiation). This way, we will only have to add another one of these classes when we add a new variable to our data model.
  - [x] update params of `test_generate_context`
  - [x] create simple test to check that all classes have URIs for their schemaKey in the `@context`
  - [x] regenerate example_synthetic.jsonld

Not currently planned:
- currently this bug is not caught by any of our tests, since we don't "expand" any example .jsonld files to view the actual generated graph model. Maybe we could try using a jsonld parser in Python (https://github.com/digitalbazaar/pyld ?) to catch some of these non-URI `@types`

**Comment by alyssadai** [comment]
@surchs let me know what you think of the spec

**Comment by surchs** [comment]
> add back a separate named class for each controlled term

I think I like this option better. We can keep the `ControlledTerms` class around and just inherit from it with the to-be-recreated classes and then just provide their `schemaKey` attribute. I prefer this because we will only have to add another one of these classes when we add a new variable to our data model. So there may be several of these in the future, but it will not be a very long list.

**Comment by alyssadai** [comment]
Sounds good, let's try that then

**Comment by alyssadai** [comment]
@surchs thoughts on the last point, trying to use something like pyld or [rdflib](https://github.com/RDFLib/rdflib) to try to "expand" a sample .jsonld file for to test that `@type`, etc. are expanded as expected?

**Comment by surchs** [comment]
> Sounds good, let's try that then

Can you update the specification to describe this plan.

> trying to use something like pyld or [rdflib](https://github.com/RDFLib/rdflib) to try to "expand" a sample .jsonld file

Not sure, but I'd say that's a separate issue. I wonder also if we can write a reasonably simple test to check this condition without using these rdf libraries.

**Comment by alyssadai** [comment]
Okay, spec has been updated. Moving into spec-done now, let me know @surchs if anything else is missing.
