### ISSUE TITLE
[BUG] `purl:` prefix for healthy controls (NCIT) doesn't currently have a corresponding URL

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagel-cli#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

All used prefixes in a `bagel pheno`-generated .jsonld (e.g., example_synthetic.jsonld) should expand properly to URLs in the graph.

### Current Behavior

Currently, the controlled term `purl:NCIT_C94342` is being used as the identifier for the healthy control `SubjectGroup`. This should expand to http://purl.obolibrary.org/obo/NCIT_C94342, but currently the namespaces specified in the `@context` do not include the NCIT PURL:
```json
  "@context": {
    "nb": "http://neurobagel.org/vocab/",
    "snomed": "http://purl.bioontology.org/ontology/SNOMEDCT/",
    "nidm": "http://purl.org/nidash/nidm#",
    "cogatlas": "https://www.cognitiveatlas.org/task/id/",
...
```

I think a few things need to be decided/done to address this.
- [x] a prefix and corresponding URL for the NCIT namespace need to be added to mappings.py
- [x] decide whether we want to stick to `purl` for the prefix, or (probably) go with something more descriptive like `ncit`
- [x] update context generation function
- [x] (maybe) once the namespace is added, write a test in the CLI to check that all used prefixes exist in the context & have a corresponding `http...` value
- [x] update example files
  - data dictionaries and jsonld files (context and values)

**Comment by surchs** [comment]
Demoting because not linked to OHBM/OpenNeuro priority - please ping here if you disagree

**Comment by alyssadai** [comment]
@surchs sadly, it looks like having a URL in the `@context` end with `_`, as in `"ncit": "http://purl.obolibrary.org/obo/NCIT_"`, doesn't allow it to expand properly in JSONLD 😢 (at least, in the JSONLD playground the term for an instance remains `ncit:<someid>`).

In light of that, any preference for sticking with the obo URL vs. bioontology one? i.e.,
```json
"ncit": "http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#" 
vs.
"ncit": "http://purl.obolibrary.org/obo/"
```
Like we said, the advantage of the first one is that the NCI name is in the URL as opposed to the ID itself, but the disadvantage is that full term URIs don't seem to be dereferensible. Whereas for the obo one it's the opposite.

I think since having a term ID contain the vocabulary name seems a bit unconventional to me (e.g., `ncit:NCIT_C94342` instead of `ncit:C94342`), I'm leaning towards the http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl# URL for the NCIT vocab even though the URIs won't go anywhere. Thoughts?

**Comment by surchs** [comment]
> looks like having a URL in the @context end with _ doesn't allow it to expand properly in JSONLD 😢 

:cry: ah, bummer

> I'm leaning towards the http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl# URL for the NCIT vocab

Me too. Not going anywhere is not great, but not terrible either. And long term, NCIT might be going away to be replaced by something else anyway. So I think your suggestion is a good solution

**Comment by alyssadai** [comment]
Blocked until https://github.com/neurobagel/neurobagel_examples/pull/10 is merged b/c tests of reference examples will fail.

**Comment by alyssadai** [comment]
See https://github.com/neurobagel/documentation/pull/88 for the docs updates
