### ISSUE TITLE
[ENH] Add portal URI and datalad IRI to dataset model

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagel-cli#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

In https://github.com/neurobagel/project/issues/119 we decided that the dataset model needs to gain two new attributes:
1. Something to contain a dereferencable URI to a website describing the data for humans, and possibly access instructions (optional). Working title `hasPortalURI`
~2. Something to contain a filesystem path or datalad ID to where the data are located (ideally machine resolvable). (required). Working title `hasFilePath`~

### Steps to implement
- [X] add optional `hasPortalURI` attribute to `Dataset` model
  - [x] expand help text: option represents a website/webpage with dataset access instructions and/or a dataset description (almost like a DOI - since most datasets with a URL will include access instructions)
~- [X] add required  `hasFilePath` attribute to `Dataset` model~
- [x] Keep `--pheno` and `--dictionary` required opts for `bagel pheno`
~- [x] For `bagel pheno` command, add a required command line arg `--dataset_dir`~
~- [x] Change `--pheno` and `--dictionary` to be optional and, if provided, must be located somewhere inside the `--dataset_dir` (one level separation only)~
  - [x] (**already in README**) clear documentation how users running CLI in container can still get the full file system path "parsed" by `bagel bids` (e.g. "please bind dataset dir to same path inside container").
- [x] Probably some type of visual / logging confirmation on what path the `bagel pheno` and `bagel bids` "sees" for the dataset to help fix the problem of people not reading these great new documentation examples
- [x] Dataset `hasPortalURI` should probably be user supplied via another optional arg in `bagel pheno`
  - [x] implement + test some validation to check that it's a URL
- [x] update tests of outputted `@context` to include new dataset attributes
- [x] regenerate example_synthetic.jsonld and example_synthetic_pheno-bids.jsonld
- [x] add tests that these attributes appear correctly in the output jsonld
- [x] update README

**Comment by surchs** [comment]
yeah, good idea. Let's keep it consistent (or change both eventually).

**Comment by alyssadai** [comment]
@surchs, mind taking a look at the "Steps to implement" part of the spec to see if things make sense?

**Comment by surchs** [comment]
@alyssadai: I looked over it. Makes sense to me. I made some minor changes to the points
- filePath is required
- getting correct filepath in container is trickier and needs  clear docs and maybe also new functionality

**Comment by alyssadai** [comment]
From our chat today, here's my current thoughts/plan for adding a dataset property `hasFilePath`:

- Must be a required attribute because the dataset file path is what we currently use as the common unique dataset identifier across data in the dataset-level and subject-level csvs outputted by the query tool (https://github.com/neurobagel/documentation/wiki/Query-Tool#example-data)
- Must be available even if dataset has only tabular data (i.e., doesn't run through `bagel bids` command)

Implementation steps
- For `bagel pheno` command, add a required command line arg `--dataset_dir`
- Change `--pheno` and `--dictionary` to be optional and, if provided, must be located somewhere inside the `--dataset_dir` (one level separation only)

**Comment by surchs** [comment]
@alyssadai: I think the new spec looks mostly good. But I do have one question:

If we no longer have any attribute to contain the "path where you can find the root of this dataset", then there would not be a way to describe how to access data without sessions / imaging informations, correct? Because then only the session nodes would have the `sessionFilePath` attribute. 

I think that's OK for where we are and what we focus on. But I do think we should then have a feature-request / feature-idea issue open on the cli/data-schema repo to explain this edge case and how we could address it. Just so we don't forget and don't have to rethink our solutions in the future.
