### ISSUE TITLE
[ENH] Datamodel: add label attribute to session 

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagel-cli#142]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### New feature

In https://github.com/neurobagel/project/issues/119 we discussed that the session object in the data model does not currently have a human readable label. For example a BIDS session might be called `ses-01` but we currently cannot represent this information. 

The goal is to 

- [ ] add this label to the data model and 
- [ ] make sure the CLI parses this information from the BIDSLayout object

**Comment by rmanaem** [comment]
Duplicate of #79
