### ISSUE TITLE
[ENH] Update `example_synthetic.json`  to be a comprehensive reference example

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagel-cli#144]
### Steps to implement
- [x] ensure all valid fields/attributes are present in the phenotypic data dictionary
  - [x] Add missing value annotation for age, sex, diagnosis
- [x] update corresponding `example_synthetic.tsv`
- [x] update `pheno` command to only assign value for sex if not missing (like for assessment / dx)
- [x] ensure tests still pass
- [x] regenerate `example_synthetic.jsonld`
- [x] generate example .jsonld output of `bagel bids` command
- [x] update test data README

**Comment by alyssadai** [comment]
@surchs, since the `example_synthetic.tsv` also needs to be updated alongside the data dict to have comprehensive examples of missing values (for age, sex, and diagnosis), and this tsv technically corresponds to the bids-examples `synthetic` dataset (https://github.com/bids-standard/bids-examples/tree/d8455af1def5e7401f212c0c7c98524776035005/synthetic), do you agree that it's fine if we deviate from the age/sex values in the original [participants.tsv](https://github.com/bids-standard/bids-examples/blob/d8455af1def5e7401f212c0c7c98524776035005/synthetic/participants.tsv)?

The `bagel bids` command currently doesn't check for alignment with the `participants.tsv` in a given BIDS dataset at all, I don't think (so the change shouldn't break anything), but just thought I'd double check

**Comment by surchs** [comment]
> do you agree that it's fine if we deviate from the age/sex values in the original [participants.tsv](https://github.com/bids-standard/bids-examples/blob/d8455af1def5e7401f212c0c7c98524776035005/synthetic/participants.tsv)

Yes! And we have already done so. our `participants.tsv` for the synthetic dataset has different values (e.g. for age) and additional columns already.

> The bagel bids command currently doesn't check for alignment with the participants.tsv in a given BIDS dataset at all

That's on purpose, at least to me. For example, in mr_proc all the relevant phenotypc information will be in the `bagel.tsv` file that may contain many more subjects than the corresponding BIDS-participants.tsv file. That's also why the user needs to tell us which file to parse, we won't just assume it's the participants.tsv file. 

Thanks for checking! important questions

**Comment by Remi-Gau** [comment]
> That's on purpose, at least to me. For example, in mr_proc all the relevant phenotypc information will be in the `bagel.tsv` file that may contain many more subjects than the corresponding BIDS-participants.tsv file. That's also why the user needs to tell us which file to parse, we won't just assume it's the participants.tsv file.

Note that you may wanna capture that somewhere in the user facing doc.

(not the fact about mr_proc) but that the cli tool is more flexible for its input than what "vanilla" BIDS would imply.
