### ISSUE TITLE
Prepare for first tagged release

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagel-cli#147]
Process to be followed described on https://github.com/neurobagel/documentation/wiki/Release-process

we want to release the cli, so that we can mint a citable DOI for it.

Steps:

- [x] Pick a semver version (see below discussion, if in doubt, let's go with 0.1.0)
- [x] Follow [these descriptions](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) so Zenodo can mint a DOI for our release of the API
- [x] add a citation.cff files + validation workflow with basic metadata
  - see: https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md
- [x] enable tracking of the repository by Zenodo **before** making a release
- [x] make a release on github (see https://github.com/neurobagel/documentation/wiki/Release-process)
  - stick to basic description of features
- [x] confirm that a DOI has been minted and dereferences to our codebase

**Comment by surchs** [comment]
releasing as v0.1.0

**Comment by surchs** [comment]
Here is the release draft: https://github.com/neurobagel/bagel-cli/releases

**Comment by alyssadai** [comment]
Release notes look good @surchs! 🧑‍🍳
