### ISSUE TITLE
[ENH] Have a jsonschema serialization of our data models

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagel-cli#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

When looking at a data dictionary I would like to get a quick idea if it is valid according to our current data model or not.
Right now I need to either make a schema from the data dictionary model classes myself or run the `bagel pheno` command on the file. It would be much faster if I had a jsonschema that I could use with any validator.

We could even look into whether https://linkml.io/ can help us with that. 
The other place to look for inspiration for is, as usual: https://github.com/dandi/dandi-schema and how they auto-populate https://github.com/dandi/schema/tree/master/releases

**Comment by alyssadai** [comment]
@surchs, can we close this now that we have this guy https://github.com/neurobagel/bagelschema/blob/main/neurobagel_data_dictionary.schema.json?

**Comment by surchs** [comment]
thanks @alyssadai, agreed!
