### ISSUE TITLE
Make output .jsonld file name user configurable

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagel-cli#157]
currently our output .jsonld files all get the same name:

- pheno: pheno.jsonld
- bids: pheno_bids.jsonld

That's not super informative, and it doesn't work well if we run the CLI for more than one dataset and put all outputs in the same place. So we need:

- [x] keep the current defaults in order not to break things
- [x] replace the output directory option with a file-path that includes the name (but keep the name `--output`)
- [x] make sure the file does not exist yet, but if it does, only allow if `--overwrite` is also true
- [x] add a `--overwrite` flag to overwrite
- add test that:
  - [x] if CLI not invoked with value for `--output`, an output file with the default name is created in the current dir
  - [x] if CLI not invoked with `--overwrite` but output file already exists, a warning is emitted

**Comment by surchs** [comment]
@alyssadai please give minimal context for when we get to speccing this
