### ISSUE TITLE
Have predictable docker image builds

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagel-cli#161]
we currently don't pin any dependency versions for the CLI. So everytime I build a docker image (currently on every push to main), I get 

1. have to rebuild all the layers of my image, because 
2. some dependency has most likely changed

and that's not nice, because the runtime environment changes in ways I can't easily understand or control.

We should instead make sure that we control the versions that the Docker image are built with. Maybe something like poetry would make sense for this.

**Comment by Remi-Gau** [comment]
pip freeze may be easier than poetry, no?

**Comment by alyssadai** [comment]
@surchs, I think we can close this issue now that we have our [requirements.txt](https://github.com/neurobagel/bagel-cli/blob/main/requirements.txt) and [dev-requirements.txt](https://github.com/neurobagel/bagel-cli/blob/main/dev_requirements.txt).

Agree?
