### ISSUE TITLE
Loosen constraints for missing assessment tool

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagel-cli#175]
Right now we assume that if you have several columns linked to the same assessment tool, if any of these has a missing value, then the participant doesn't "have" the tool. 

That's not great for several reasons:
1. The data owner in their infinite wisdom may have decided to discretize a continuous raw score and spread the information across several columns. Then, by definition, only one column would have a non-missing value
2. The fact that the other columns have information still means that there is something to be learned for this participant. The non-missing columns are probably still useful

Not saying we should add many complex heuristics to determine presence or absence. Any or All might be enough.

This limitation is currently documented internally: https://github.com/neurobagel/documentation/wiki/Neurobagel-Data-Model-limitations#assessment-tool-availability-is-too-strict

TODO
- [x] Model a tool as "Available" if **ANY** column that `isPartOf` that tool has a non-missing value

**Comment by alyssadai** [comment]
@surchs

**Comment by surchs** [comment]
@alyssadai take a look at these tasks, tell me if there's something missing

**Comment by alyssadai** [comment]
Hey @surchs, this is looking good to me. I've added a link to the docs page where we describe the current missing value behavior for assessments.

> provide a guide for rerunning the CLI on existing data (tell folks it's OK, no harm done, just run again)

For this point, would something like a new section on this page https://neurobagel.org/updating_dataset/#updating-the-graph-database called "If you want to switch to a newer version of the data model" work? Or maybe a tip on the [CLI docs page](https://neurobagel.org/cli/)?

**Comment by surchs** [comment]
Yeah, for the "what to do on breaking change" I was thinking mostly a reassuring section somewhere visible that says: not to worry, your old data dictionaries are still good. We'll just make a new graph from them like this: ... 
and then the text you suggested.

**Comment by surchs** [comment]
Ah, last question before we can get started: should we split this task? It seems pretty big and maybe involves multiple repos.

**Comment by alyssadai** [comment]
I've moved the documentation subtasks  to this [issue](https://github.com/neurobagel/documentation/issues/121). Think this issue should be ready to go now, wdyt?

**Comment by surchs** [comment]
I moved https://github.com/neurobagel/documentation/issues/121 also into Specify - Done since we split it off of this guy.
