### ISSUE TITLE
Migrate to Pydantic v2

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagel-cli#180]
The release of Pydantic V2 introduced several breaking changes in the code due to name changes of multiple methods, removed or deprecated types/methods/objects, and broader changes to the logic of fields, validators, + more.

The docs for V2 have _not quite_ caught up to the changes yet, but there is a comprehensive migration guide 🎉 
- https://docs.pydantic.dev/dev-v2/migration/ and pretty detailed `PydanticUserErrors`
- (new!) https://github.com/pydantic/bump-pydantic

Related are:
#179

TODO: 
- [x] investigate needed refactor for moving to pydantic 2
- [x] refactor to enable pydantic 2 and migrate

**Comment by alyssadai** [comment]
Any thoughts @surchs?

I've started making some of the necessary changes (based on currently failing tests) in a branch and think the migration shouldn't require any major rewrites on our end, but some of the updates related to deprecated methods would probably benefit from a closer look as they involve a bit of extra code to preserve existing behavior.

**Comment by surchs** [comment]
Bumping this up since my ill advised late night commit (https://github.com/neurobagel/bagel-cli/commit/1d4cb5217813cedfbe6d78fcb2821fac72059089) to main has made this an actual blocker.

**Comment by alyssadai** [comment]
Will pin pydantic version for now. Taking this issue off of backlog in favour of #184.
