### ISSUE TITLE
Add requirements.txt pinning all versions of dependencies

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagel-cli#184]
Ensures version bumps don't affect our codebase behaviour in unexpected ways.
See also: #180 and #179

- [x] Create pinned dependencies for Docker
- [ ] Prevent Dependabot from bumping Pydantic (to 2)
- [x] Protect the main branch from direct commits 👀 
- [x] Update Dockerfile to use new requirements.txt

**Comment by surchs** [comment]
Until we think of a better solution, I'd say we just use https://github.com/jazzband/pip-tools/ to handle pinning of dependencies for us. `requirements.txt` will turn into `package-lock.json` and we can always run `pip-compile` again to update.

wdyt @Remi-Gau? It's not poetry :)

**Comment by surchs** [comment]
Not sure how dependabot will deal with these changes, so I'm not making any configurations yet
