### ISSUE TITLE
Add `neurobagel/neurobagel_examples` as submodule

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagel-cli#187]
- [x] Remove reference synthetic example files in CLI
- [x] Update paths used for tests

**Comment by rmanaem** [comment]
@alyssadai 
> Remove reference synthetic example files in CLI

Just double checking does this refer to the 4 files from https://github.com/neurobagel/neurobagel_examples/issues/2?

**Comment by alyssadai** [comment]
@rmanaem yes

**Comment by surchs** [comment]
did you both find a solution for this issue? If not, @rmanaem can you please add a draft PR to show the CI breaking?

**Comment by alyssadai** [comment]
@surchs we did identify a solution for the CI breaking! It’s due to the test workflow still using our old dependency installation method rather than our new requirements.txt - so the tests were using a newer ver of pandas that had a deprecation warning breaking some of the assertions. @rmanaem will open a small separate PR for the fix in addition to for this issue

**Comment by surchs** [comment]
thanks for clarifying!
