### ISSUE TITLE
Release 0.1.1 of CLI including tagged Docker Hub image

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagel-cli#236]
#234 introduces a breaking change to the CLI's handling of missing values for assessment tools

TODO:
- [x] release v0.1.1 of CLI on GitHub
- [ ] create + push Docker image tagged 0.1.1 to Docker Hub

**Comment by alyssadai** [comment]
For reviewer: see draft release notes here https://github.com/neurobagel/bagel-cli/releases/edit/untagged-af73b5845c77b1c86475

I'm not entirely convinced on the emoji I selected for "data model changes", here are some other contenders:
:link: :test_tube: :label:

**Comment by surchs** [comment]
I'm getting a 404 on the link you posted Alyssa

**Comment by surchs** [comment]
Nice! I like the ⚙️ for data model changes! Release notes look good. 

🧑‍🍳

**Comment by alyssadai** [comment]
Tagged Docker image has also been pushed, see https://hub.docker.com/r/neurobagel/bagelcli/tags.

Closing this issue as completed now!
