### ISSUE TITLE
Investigate Coveralls failure about "parallel builds"

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagel-cli#238]
This issue has recently crept up in this repo (so far only): 

Coveralls fails on the Python 3.10 runner (so far I have only seen it on that version) with the following error:

```
Can't add a job to a build that is already closed. Build 6829765660 is closed. See docs.coveralls.io/parallel-builds
```
See e.g. [here](https://github.com/neurobagel/bagel-cli/actions/runs/6829765660/job/18576530954?pr=237#step:7:72)

The docs in question: docs.coveralls.io/parallel-builds

We should investigate why this happens and if it is on our side or their side

**Comment by surchs** [comment]
Just rerunning the failed test does not seem to help. But simply pushing an empty or almost empty commit to the PR branch appears to reliably resolve the error. See e.g. #237 

@alyssadai was this also your experience?

**Comment by alyssadai** [comment]
Yep. I also found https://github.com/lemurheavy/coveralls-public/issues/1716, which seems relevant but I was discouraged by the long thread and so have not yet read it in detail 🙈

**Comment by surchs** [comment]
also see: https://github.com/neurobagel/planning/issues/89
