### ISSUE TITLE
Enable parsing of BIDS dataset with data dictionary

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagel-cli#27]
This tracks the work to create a `bagel add-bids` subcommand that does this:

Inputs:
(1) pheno.jsonld generated by `bagel pheno`
(2) BIDS dataset directory path
(3) maybe: the path on the host computer of the BIDS dataset
Output: pheno_bids.jsonld

A user who has already run `bagel pheno` (https://github.com/neurobagel/bagelbids/issues/32) successfully to create a `pheno.jsonld` file should be able to use this subcommand to add imaging metadata (BIDS) to the existing `pheno.jsonld` file. The imaging metadata to add are:

- the type of imaging acquired during a session as Acquisition
- the absolute file system path of a session directory in the BIDS dataset

Expectations (for now):
- subject IDs in the pheno.tsv and the corresponding BIDS directory will be the same. 
- there may be subjects in the pheno.tsv file that do not exist in the BIDS directory (i.e. pheno only)
- if a subject does not exist in the BIDS dir, it will remain in the .jsonld with only the existing phenotypic metadata
- if a subject has multiple acquisitions of the same type in the same session (e.g. several T1s), then they should be added as separate acquisitions to the session (i.e. you can have more than one T1 in a session)

Things to do:

- [x] #76
  - this will require refactoring the existing `bids pheno` CLI tests because the CLI will have to be called with the explicit subcommand name whereas we can currently just call it with the cli name (i.e. `bagelbids --somearg` vs `bagelbids pheno --somearg`)
- [x] #77
  - the pheno.jsonld is currently only valid after we remove the `@context` tag
  - we can investigate if there is a way to adjust the data dictionary schema to also allow for the `@context` while still rejecting invalid data dictionary instances. but stripping the`@context` is also a valid solution for now
- [x] #29 
- [x] #79
  - essentially matching subjects by label and adding new imaging related attributes without deleting the existing information (or changing the subject identifier / reinstantiating any of the dataset / subject / sessions instances)
- [x] #82
- [x] #4 
  - get the absolute file system path, even if the path to the BIDS directory was provided as a relative path
  - add file path attribute to model schema for a session
- [x] #83
  - add the `@context` back in, if it was previously stripped
  - make sure the existing phenotypic metadata is still there / the same / unchanged
  - make sure the BIDS imaging data matches our expectations from looking at the input data

**Comment by alyssadai** [comment]
@surchs I think this one can be closed as well, but want a second pair of eyes before doing so.

**Comment by surchs** [comment]
@alyssadai agreed! Let's close :tada:
