### ISSUE TITLE
[BUG] Dash in a column name breaks the pheno parsing

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagel-cli#312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

When I have a column `BIDS-ID` in my `.json` data dictionary

### Current Behavior

The CLI breaks at the pheno command

### Error message

```
UndefinedVariableError: name 'BIDS' is not defined
```
Likely because the column name is split at the `-` somehow

### How to reproduce

Make a column name with `BIDS-ID` in the `.json` data dictionary (and the .tsv)

### Anything else?

It looks like when accessing (?) the data dictionary key, for some reason only the first part before the hyphen is read. As a result, the column "BIDS" is searched for in the TSV, which returns no matches. This hyphen weirdness might be due to the utilities we're using to parse JSON in the CLI, but needs some more investigating.

Switching "BIDS-ID" to "BIDS_ID" in both the TSV & JSON resolved the error.

**Comment by alyssadai** [comment]
Looks like this line is the culprit:

https://github.com/neurobagel/bagel-cli/blob/be5364e13f5f0c5c53011daa54a70b333c48e370/bagel/cli.py#L100

pandas `query` function doesn't allow hyphens, spaces, etc. in column names, they must be escaped with backticks.

https://stackoverflow.com/questions/50746726/how-to-use-query-method-of-pd-dataframe-objects-with-columns-that-have-hyphe
