### ISSUE TITLE
[BUG] TSV file with non-utf-8 encoding produces cryptic UnicodeDecodeError

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagel-cli#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

When running the `bagel pheno` command on a TSV and JSON that were successfully processed by the annotation tool, a JSONLD is successfully generated.

### Current Behavior

CLI exits with a UnicodeDecodeError and traceback, but it is not immediately clear from the error that it is due to a file encoding problem (or which input file is the culprit).

### Error message

`UnicodeDecodeError: utf-8 can't decode byte 0xeb in position ...: invalid continuation byte`

### Environment

- OS: Linux
- Python/Node version:

### How to reproduce

- Run `bagel pheno` on a TSV with a non-utf encoding (e.g., `latin1`) and the corresponding JSON from the annotation tool

### Anything else?

For simplicity and to avoid slowing down the CLI, we should probably resolve this for now by:
- [x] explicitly specifying the utf-8 encoding when reading in the TSV (and JSON?)
- [x] catch and emit an informative error to the user when either input is not in UTF-8
- [x] provide a link or name of a tool the user can use to convert their files

To avoid the TSV / JSON potentially becoming incompatible after encoding conversion, we should implement a similar check in the annotation tool.

**Comment by alyssadai** [comment]
Wdyt @surchs about the proposed solution?

**Comment by alyssadai** [comment]
@surchs, this error is reproducible with the abide2/GU_1 dataset from INDI.

**Comment by surchs** [comment]
Hey @alyssadai, agreed, your proposed solution makes sense. Let's do that!
