### ISSUE TITLE
Investigate schema and examples for the Nipoppy imaging bagel

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagel-cli#344]
TODO

- [x] Figure out if Nipoppy already has a schema for the imaging bagel
- [x] Figure out what the near future imaging bagel schema is going to look like
- [x] Contribute a schema for the imaging bagel to nipoppy if wanted, then integrate / link this schema here (CLI repo). If nipoppy doesn't want a schema contributed, just create the schema here via pydantic
- [x] Find or create an example instance of a nipoppy imaging bagel and make it accessible here (i.e. by adding it to the neurobagel examples repo and updating our submodule of the neurobagel examples repo)
- [x] Add new prefix namespace for Nipoppy pipeline terms (allowed names & versions)

NOTES:
- Nipoppy schema is in Pydantic v2, so we should probably see if we can use the jsonschema from their model instead for compatibility w/ our v1 CLI

**Comment by surchs** [comment]
Here is a link to the current latest nipoppy imaging bagel schema in the docs: https://nipoppy.readthedocs.io/en/latest/schemas/index.html#bagel-file

And here is the corresponding pydantic model from nipoppy: https://github.com/nipoppy/nipoppy/blob/756fb3532cc201986300ae2b0095429e179e5a9a/nipoppy/tabular/bagel.py

Finally, here is a currently open PR that has some proposed changes to the bagel schema: https://github.com/nipoppy/nipoppy/blob/756fb3532cc201986300ae2b0095429e179e5a9a/nipoppy/tabular/bagel.py

**Comment by alyssadai** [comment]
Note: we probably also want to update the subject IDs from the Nipoppy example to be the same or a subset of IDs we're currently using in the [reference example phenotypic data](https://github.com/neurobagel/neurobagel_examples/blob/main/data-upload/example_synthetic.tsv), so that we don't run into issues when testing the pheno command along with the new IDP command.
