### ISSUE TITLE
update `bagel bids` subcommand to play nice with new derivatives

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagel-cli#346]
TODO

update the `bagel bids` command to
- [x] accept either a `pheno.jsonld` (output of `bagel pheno`) or a `pheno-derivatives.jsonld` (output of `bagel derivatives` #345) as input
- [x] update help text
- [x] find and match existing imaging sessions between a provided `pheno-derivatives.jsonld` and a raw BIDS dataset so that we do not recreate imaging sessions if the derivatives subcommand has already created them
  - [x] if session is missing, add to potentially existing "ses-nb01"?

Related to #345

**Comment by alyssadai** [comment]
Closed by #349
