### ISSUE TITLE
[BUG] Unrecognized pipelines when adding imaging derivatives

### ISSUE THREAD

**Issue by michellewang** [neurobagel/bagel-cli#372]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Expected Behavior

`fmriprep`, `freesurfer`, and `mriqc` are recognized as valid pipelines since they are in the [Nipoppy pipeline catalog](https://github.com/nipoppy/pipeline-catalog/tree/main/processing)

### Current Behavior

Getting an error. Seems like `KNOWN_PIPELINE_URIS` is empty -- perhaps the container doesn't include the pipeline catalog?

### Error message

```
│ /usr/local/lib/python3.10/site-packages/bagel/derivatives_utils.py:26 in                         │
│ check_pipelines_are_recognized                                                                   │
│                                                                                                  │
│   23 │   │   set(pipelines).difference(mappings.KNOWN_PIPELINE_URIS)                             │
│   24 │   )                                                                                       │
│   25 │   if len(unrecognized_pipelines) > 0:                                                     │
│ ❱ 26 │   │   raise LookupError(                                                                  │
│   27 │   │   │   f"The processing status file contains unrecognized pipelines in the column '    │
│   28 │   │   │   f"{unrecognized_pipelines}. "                                                   │
│   29 │   │   │   f"Allowed pipeline names are the following pipelines supported natively in N    │
│                                                                                                  │
│ ╭───────────────────────────────────── locals ──────────────────────────────────────╮            │
│ │              pipelines = array(['fmriprep', 'freesurfer', 'mriqc'], dtype=object) │            │
│ │ unrecognized_pipelines = ['fmriprep', 'freesurfer', 'mriqc']                      │            │
│ ╰───────────────────────────────────────────────────────────────────────────────────╯            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
LookupError: The processing status file contains unrecognized pipelines in the column 'pipeline_name': ['fmriprep', 'freesurfer', 
'mriqc']. Allowed pipeline names are the following pipelines supported natively in Nipoppy (https://github.com/nipoppy/pipeline-catalog): 
{}
```

### Environment

`bagelcli v0.3.1`

### How to reproduce

Use PPMI derivatives files I shared separately

**Comment by michellewang** [comment]
Did some investigating and indeed  `bagel.mappings.PROCESSING_PIPELINE_PATH` points to `/usr/local/lib/python3.10/site-packages/pipeline-catalog/processing` inside the container which does not exist. The pipeline catalog probably got lost when building the Python package. And maybe the tests don't fail because they are run from the Git repo which has the pipeline catalog?

**Comment by alyssadai** [comment]
@surchs, I can fix the workflows, but do you think it would make sense to also error out & exit immediately in the CLI when fetching allowed pipelines returns an empty array?

i.e., somewhere here:

https://github.com/neurobagel/bagel-cli/blob/66111d49d468e3debe20645ac083b47e47aa153c/bagel/mappings.py#L46-L73

Alternatively, we could discuss that in a separate issue.

**Comment by surchs** [comment]
Agree that we need to fix the prod-is-different-from-testing issue separately, I linked this issue to a point on that matter it in the tech-debt collection issue. 

Erroring out for missing pipelines sounds OK, I'd say only for the `derivatives` subcommand though.
