### ISSUE TITLE
change repo name

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagel-cli#57]
Once we're done with the refactoring of the CLI, we should rename the repo to align with the other neurobagel repos. I think the plan is for this one to just be called `neurobagel/cli`.

**Comment by alyssadai** [comment]
I don't have a particularly strong opinion on this, but is `cli` too general do you think? Since this tool does have a fairly specific purpose rather than just being a command-line interface to all Neurobagel functionality. Some alternatives could be `parser` or `data-mapper` or something to do with dictionaries?

**Comment by surchs** [comment]
Good question. My thinking was: "are we likely to make another repo for other CLI related things?". I currently don't think so. We have three things to convey functionality with the name:

- the repo name (e.g. `cli`)
- the CLI command name (e.g. `bagel`)
- the CLI subcommand name (e.g. `pheno` or `process`)

Only the last two are really seen by the user when they run the tool, the repo name is more for visibility / us. I think we're generally moving to shorter repo names now. But open to suggestions for all three temp names above.

**Comment by surchs** [comment]
I think I'm leaning towards `bagel-cli` for the repo name. When you clone it without explicitly setting a dir name just having `cli` is not that much info to tell you what it is (assuming you don't just have neurobagel repos)

**Comment by surchs** [comment]
> Reminiscent of dandi-cli also

:shushing_face: 

> Do you feel similarly about the other repos

you mean the `api`? Yeah I guess that is the same case. I really don't have very strong feelings about the repo name, other than that it should probably not be `bagelbids` anymore.
