### ISSUE TITLE
Use consistent terminology for data elements, categories, and columns

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagel-cli#60]
we keep having issues with synonyms or similar sounding terms. Some examples are:

- Data model and data dictionary
- category and common data element
- category and categorical or continuous columns in a .tsv

We should choose the most descriptive names, document them in our docs and then use them consistently.

- [ ] decide on the language we want to use for all these things
- [ ] https://github.com/neurobagel/documentation/issues/44

_Originally posted by @surchs in https://github.com/neurobagel/bagelbids/pull/58#discussion_r1104896311_

**Comment by surchs** [comment]
I thought this was linked to https://github.com/neurobagel/project/issues/78 but now reading it again, I realize that is not. I'll move it to the roadmap for now because it is not a priority in my view. Disagree @alyssadai ?

**Comment by alyssadai** [comment]
Agreed, sounds good @surchs ! I've updated https://github.com/neurobagel/project/issues/78 to reflect this.

**Comment by surchs** [comment]
Linked to https://github.com/neurobagel/documentation/issues/44

**Comment by alyssadai** [comment]
Merged with https://github.com/neurobagel/documentation/issues/44
