### ISSUE TITLE
Resolve name conflicts between properties and resources

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagel-cli#65]
Currently, several resources and properties defined in the controlled vocabularies used by Neurobagel have the same name. To resolve namespace clashes and minimize confusion, we need to:
- [x] Pick distinct naming conventions for namespaces as well as properties (e.g., prefixed with `has`, such as `bg:hasAssessment`) vs related resources (e.g., `bg:Assessment` - capitalized) in the graph and document it in the user-facing docs
  - see https://github.com/neurobagel/encarta/issues/10
- [x] Update terms used by API query template and data model used by CLI
  - [x] #124
  - [x] #89
- ~[ ] Ensure data in graph conforms to the same vocabulary~

**Comment by surchs** [comment]
@alyssadai as we just discussed in https://github.com/neurobagel/bagel-cli/pull/119, it would be good to also have a central location where we list for reference:

- our convention for namespace shorthands (e.g. `bg` for `neurobagel.org`, etc)
- names and capitalization for properties/graph edges (e.g. `hasSession`)
- names and capitalization for classes/graph nodes (e.g. `Dataset`)

This could be a page on the documentation, or some other easily referencable thing. Probably it's own issue to be split off from this one.

**Comment by alyssadai** [comment]
Closing as completed. Moved tracking of aligning MNI graph data to separate issue https://github.com/neurobagel/project/issues/109
