### ISSUE TITLE
change the package name

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagel-cli#80]
We have three places for names:

1. The name of the repository
2. The name of the python package in the repository
3. The name of the CLI program / entrypoint

All three of these should probably either align or be very close.
So far we have renamed the CLI to just `bagel` + some subcommand. In #57 we have renamed the repository to `bagel-cli`. So the only thing left to do is to also rename the python package name to something similar. I guess `bagel-cli` is good enough as a package name. 

README also needs to be updated.

**EDIT:** Since Python package names can't include a hyphen, the repo name will be kept as `bagel-cli` and the package itself and CLI program will be called `bagel`

**Comment by alyssadai** [comment]
Just peeped what dandi did for their [CLI](https://github.com/dandi/dandi-cli) and they have `dandi-cli` as the repo name but `dandi` as the package name, just like our current setup. I wouldn't be opposed to keeping what we have now, if only to minimize the number of hyphens a user has to type to use our CLI 😛. Thoughts?

**Comment by surchs** [comment]
I'm good with `bagel-cli`! But the package is currently still called `bagelbids`, so the idea would be to change it to the new name.

**Comment by alyssadai** [comment]
Ah, I understand! Will do.
