### ISSUE TITLE
If user provides .csv instead of .tsv, bagel pheno CLI fails with nice looking but incorrect error

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagel-cli#90]
If I provide `bagel pheno` with a .csv instead of a .tsv file (i.e. comma separated data instead of tab separated), it crashes with 

```
LookupError: The provided data dictionary and phenotypic file are individually valid, but are not compatible. Make sure that you selected the correct data dictionary for your phenotyic file. Every column described in the data dictionary has to have a corresponding column with the 
same name in the phenotypic file
```

That's only a little bit better than crashing somewhere completely unexpected in the code, and definitely worse than crashing when the .tsv is loaded with some informative error message. The reason for it not crashing sooner is that a .csv is technically a valid .tsv that has only one column / no tabs anywhere.

I think we should:

- [x] validate that the pheno file has a .tsv file ending (not a guarantee, but a good start). we should probably fire a warning
- [x] if the loaded pheno file has only one column, then we can probably error out. Because the best case is that it only contains the participantID column. But a more likely case is that something went wrong with parsing the pheno file

**Comment by alyssadai** [comment]
@surchs without having thought about this too deeply, couldn't we accept csv files as well and just change the `sep` param during the `read_csv` step depending on the input file ending?

**Comment by surchs** [comment]
I vote against supporting .csv. It's true that this probably would only need a small change to enable. But it also means we now promise to everyone that they can come with .csv files and we will support them, leaving us with the responsibility to fix and test problems with two different file formats. Converting .csv to .tsv is pretty reasonable and simple for an individual user (you can even do it with Excel), and so it makes sense to me to put the burden on the user for this. Its also good to have a clear answer to "what do I need to do to my data to use your tools" and a simple "bring .tsv" is pretty clear. BIDS is doing well with this constraint, so I think we should as well.

**Comment by alyssadai** [comment]
Ok, that's fair. In that case, let's go with your proposed solution of erroring out when the input is not a .tsv. Actually, maybe I should update the dashboard to reflect this as well, so that there's consistency in the types of file formats supported by both tools (right now it expects a `bagel.csv`)

**Comment by surchs** [comment]
Yeah, I think being consistent across both tools is a good idea. We should probably also get @nikhil153 into this conversation to see if we could default mr_proc to .tsv directly

**Comment by nikhil153** [comment]
Sure, we can generate `bagel.tsv` files from now on.

**Comment by surchs** [comment]
Thanks @nikhil153, this wasn't meant to be the form of us asking you to change the format. Just thought I include you here. But yes, bagel.tsv would make it easier for us.
